# Generated by Django 5.1.7 on 2025-05-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('Title', models.CharField(max_length=100)),
                ('MovieID', models.IntegerField(primary_key=True, serialize=False)),
                ('Rating', models.FloatField()),
                ('ReleaseDate', models.DateField()),
                ('DirectorEmail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
